### ISSUE TITLE
Why is the converted data (acm/acm-objects/) spilt into 7 files?

### ISSUE THREAD

**Issue by kateblanch** [american-art/acm#16]
It would be helpful to understand the logic behind splitting the data into 7 files. Going forward, we're going to need to know on what parameter the splits were made and what purpose it serves. It's hard to manage 7 files.

**Comment by kateblanch** [comment]
https://github.com/american-art/acm/blob/master/acm_split_file.py

I see the above file was created to do the split, but if someone could translate the "why" that'd be great :)

**Comment by workergnome** [comment]
They just pull 1000 items, write it to a file, and then open the next file to write the next 1000 items.  I would bet that Karma has a limitation in the size of XML file that it can load, and this is an easy way to work around that limitation.

**Comment by caknoblock** [comment]
David is correct in that Karma can not process huge XML files.  The issue is that the processing of the data is run in Spark and that XML is not a streaming file format, so it must load the entire file into memory.  But the full XML file is too large and the system cannot handle it.  So we wrote a script that automatically divides the file into smaller files.  New data can still be published in the original single file format.
