### ISSUE TITLE
Actors and objects have the same URIs

### ISSUE THREAD

**Issue by workergnome** [american-art/acm#6]
The URI assigned to artists is identical in form to the URIs assigned to objects:

(in acm-objects.n3)
```
<http://data.americanartcollaborative.org/acm/object/103> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.cidoc-crm.org/cidoc-crm/E22_Man-Made_Object> .
```

but also

(in acm-artist.n3)
```
<http://data.americanartcollaborative.org/acm/object/103> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.cidoc-crm.org/cidoc-crm/E39_Actor> .
```

**Comment by sjayakum** [comment]
This again is fixed in my previous commit.
We have a problem generating the new triple store in the Server due to some memory error exception (which is not because of the model as locally the queries were working).
I am working on fixing this (which might involve converting the XML data into JSON form).

**Comment by bsnikhila** [comment]
This is fixed.
